from setuptools import setup, find_packages

setup(
    name='algorzen-dqtoolkit',
    version='0.1.0',
    description='Enterprise-grade data quality toolkit by Rishi R Carloni & the Algorzen team',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    author='Rishi R Carloni & the Algorzen team',
    author_email='contact@algorzen.com',
    url='https://github.com/algorzen/data-quality-toolkit',
    packages=find_packages(),
    install_requires=[
        'pandas>=2.0.0',
        'numpy>=1.24.0',
        'fastapi>=0.100.0',
        'uvicorn>=0.20.0',  # Needed for API server
        'celery>=5.3.0',
        'redis>=4.5.0',
        'sqlalchemy>=2.0.0',
        'psycopg2-binary>=2.9.0',
        'pymongo>=4.3.0',
        'pyspark>=3.4.0',
        'dask>=2023.0.0',
        'kafka-python>=2.0.0',
        'jinja2>=3.1.0',
        'rich>=13.0.0',
        'click>=8.1.0',
        'pydantic>=2.0.0',
        'python-multipart>=0.0.6',
        'aiofiles>=23.0.0',
        'openpyxl>=3.1.0',
        'pyarrow>=12.0.0',
        'scikit-learn>=1.3.0',
        'matplotlib>=3.7.0',
        'seaborn>=0.12.0',
        'plotly>=5.15.0',
        'boto3>=1.28.0',
        'azure-storage-blob>=12.17.0',
        'google-cloud-storage>=2.8.0',
        'prometheus-client>=0.17.0',
        'psutil>=5.9.0',
        'requests>=2.31.0',
        'structlog>=23.1.0',
        'cryptography>=41.0.0',
        'python-jose>=3.3.0',
        'passlib>=1.7.4',
        'python-dotenv>=1.0.0',
        'pytest>=7.4.0',
        'pytest-asyncio>=0.21.0',
        'black>=23.0.0',
        'flake8>=6.0.0',
        'mypy>=1.4.0',
        'croniter>=1.4.0',
        'email-validator>=2.0.0',
    ],
    extras_require={
        'dev': [
            'pytest>=7.4.0',
            'pytest-cov>=4.1.0',
            'pytest-mock>=3.11.0',
            'black>=23.0.0',
            'flake8>=6.0.0',
            'mypy>=1.4.0',
            'pre-commit>=3.3.0',
        ],
        'spark': [
            'pyspark>=3.4.0',
            'delta-spark>=2.4.0',
        ],
        'cloud': [
            'boto3>=1.28.0',
            'azure-storage-blob>=12.17.0',
            'google-cloud-storage>=2.8.0',
            'google-cloud-bigquery>=3.11.0',
        ],
        'ml': [
            'scikit-learn>=1.3.0',
            'tensorflow>=2.13.0',
            'torch>=2.0.0',
        ],
    },
    entry_points={
        'console_scripts': [
            'algorzen-dqt=algorzen_dqt.cli.main:main',
        ],
    },
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Intended Audience :: Science/Research',
        'Intended Audience :: System Administrators',
        'Topic :: Database',
        'Topic :: Scientific/Engineering :: Information Analysis',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Topic :: System :: Monitoring',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Operating System :: OS Independent',
        'Framework :: FastAPI',
        'Framework :: Pytest',
    ],
    python_requires='>=3.10',
    include_package_data=True,
    package_data={
        'algorzen_dqt': ['templates/*', 'static/*', 'config/*.yaml'],
    },
    keywords='data-quality, data-validation, data-governance, etl, data-engineering, compliance',
    project_urls={
        'Bug Reports': 'https://github.com/algorzen/data-quality-toolkit/issues',
        'Source': 'https://github.com/algorzen/data-quality-toolkit',
        'Documentation': 'https://docs.algorzen.com',
        'Changelog': 'https://github.com/algorzen/data-quality-toolkit/blob/main/CHANGELOG.md',
    },
)
